config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :seances
  resources :activites
  resources :directions
  resources :structures
  resources :posts
  resources :places

  root 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/structure.rb
class Structure < ApplicationRecord
  belongs_to  :direction
end

app/controllers/structures_controller.rb
class StructuresController < ApplicationController
  before_action :set_structure, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /structures
  # GET /structures.json
  def index
    @structures = Structure.all
  end

  # GET /structures/1
  # GET /structures/1.json
  def show
  end

  # GET /structures/new
  def new
    @structure = Structure.new
  end

  # GET /structures/1/edit
  def edit
  end

  # POST /structures
  # POST /structures.json
  def create
    @structure = Structure.new(structure_params)

    respond_to do |format|
      if @structure.save
        format.html { redirect_to @structure, notice: 'Structure was successfully created.' }
        format.json { render :show, status: :created, location: @structure }
      else
        format.html { render :new }
        format.json { render json: @structure.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /structures/1
  # PATCH/PUT /structures/1.json
  def update
    respond_to do |format|
      if @structure.update(structure_params)
        format.html { redirect_to @structure, notice: 'Structure was successfully updated.' }
        format.json { render :show, status: :ok, location: @structure }
      else
        format.html { render :edit }
        format.json { render json: @structure.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /structures/1
  # DELETE /structures/1.json
  def destroy
    @structure.destroy
    respond_to do |format|
      format.html { redirect_to structures_url, notice: 'Structure was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_structure
      @structure = Structure.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def structure_params
      params.require(:structure).permit(:name, :address, :zipcode, :phone, :email, :typeStructure, :direction_id)
    end
end

app/helpers/structures_helper.rb
module StructuresHelper
end

app/views/structures/_form.html.erb
<%= form_with(model: structure, local: true) do |form| %>
  <% if structure.errors.any? %>
    <div id="error_explanation" class="alert alert-primary">
      <h2><%= pluralize(structure.errors.count, "error") %> prohibited this structure from being saved:</h2>

      <ul>
      <% structure.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, id: :structure_name, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :address %>
    <%= form.text_field :address, id: :structure_address, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :zipcode %>
    <%= form.number_field :zipcode, id: :structure_zipcode, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :phone %>
    <%= form.number_field :phone, id: :structure_phone, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :email %>
    <%= form.text_field :email, id: :structure_email, class:"form-control", placeholder:"name@example.com" %>
  </div>

  <div class="form-group">
    <%= form.label :typeStructure %>
    <%= form.text_field :typeStructure, id: :structure_typeStructure, class:"form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :Direction %>
    <%= form.select :direction_id, Direction.all.collect { |d| [ d.name, d.id ] }, include_blank: false, class:"form-control" %>
  </div>

  <div class="btn btn-primary">
    <%= form.submit %>
  </div>
<% end %>

app/views/structures/edit.html.erb
<h1>Editing Structure</h1>

<%= render 'form', structure: @structure %>

<%= link_to 'Show', @structure,class:"badge badge-primary" %> |
<%= link_to 'Back', structures_path,class:"badge badge-primary" %>

app/views/structures/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Structures</h1>

<table class="table">
  <thead class="thead-dark">
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Zipcode</th>
      <th>Phone</th>
      <th>Email</th>
      <th>Type</th>
      <th>Direction</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @structures.each do |structure| %>
      <tr>
        <td><%= structure.name %></td>
        <td><%= structure.address %></td>
        <td><%= structure.zipcode %></td>
        <td><%= structure.phone %></td>
        <td><%= structure.email %></td>
        <td><%= structure.typeStructure %></td>
        <td><%= structure.direction.name %></td>
        <td><%= link_to 'Show', structure, class:"badge badge-primary" %></td>
        <td><%= link_to 'Edit', edit_structure_path(structure), class:"badge badge-primary" %></td>
        <td><%= link_to 'Destroy', structure, method: :delete, data: { confirm: 'Are you sure?' },class:"badge badge-primary" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Structure', new_structure_path, class:"badge badge-primary" %>

app/views/structures/new.html.erb
<h1>New Structure</h1>

<%= render 'form', structure: @structure %>

<%= link_to 'Back', structures_path, class:"badge badge-primary" %>

app/views/structures/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @structure.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @structure.address %>
</p>

<p>
  <strong>Zipcode:</strong>
  <%= @structure.zipcode %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @structure.phone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @structure.email %>
</p>

<p>
  <strong>Type:</strong>
  <%= @structure.typeStructure %>
</p>
<p>
  <strong>Direction:</strong>
  <%= @structure.direction.name %>
</p>

<%= link_to 'Edit', edit_structure_path(@structure), class:"badge badge-primary" %> |
<%= link_to 'Back', structures_path, class:"badge badge-primary" %>