config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :seances
  resources :activites
  resources :directions
  resources :structures
  resources :posts
  resources :places

  root 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/seance.rb
class Seance < ApplicationRecord
  belongs_to :place
  belongs_to :activite
  belongs_to :structure
end

app/controllers/seances_controller.rb
class SeancesController < ApplicationController
  before_action :set_seance, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /seances
  # GET /seances.json
  def index
    @seances = Seance.all
  end

  # GET /seances/1
  # GET /seances/1.json
  def show
  end

  # GET /seances/new
  def new
    @seance = Seance.new
  end

  # GET /seances/1/edit
  def edit
  end

  # POST /seances
  # POST /seances.json
  def create
    @seance = Seance.new(seance_params)

    respond_to do |format|
      if @seance.save
        format.html { redirect_to @seance, notice: 'Seance was successfully created.' }
        format.json { render :show, status: :created, location: @seance }
      else
        format.html { render :new }
        format.json { render json: @seance.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /seances/1
  # PATCH/PUT /seances/1.json
  def update
    respond_to do |format|
      if @seance.update(seance_params)
        format.html { redirect_to @seance, notice: 'Seance was successfully updated.' }
        format.json { render :show, status: :ok, location: @seance }
      else
        format.html { render :edit }
        format.json { render json: @seance.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /seances/1
  # DELETE /seances/1.json
  def destroy
    @seance.destroy
    respond_to do |format|
      format.html { redirect_to seances_url, notice: 'Seance was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_seance
      @seance = Seance.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def seance_params
      params.require(:seance).permit(:public, :ageMin, :ageMax, :niveau, :sexe, :periode, :jour, :heureDebut, :heureFin, :dateDebut, :dateFin, :tarif, :place_id, :activite_id, :structure_id)
    end
end

app/helpers/seances_helper.rb
module SeancesHelper
end

app/views/seances/_form.html.erb
<%= form_with(model: seance, local: true) do |form| %>
  <% if seance.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(seance.errors.count, "error") %> prohibited this seance from being saved:</h2>

      <ul>
      <% seance.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :public %>
    <%= form.text_field :public, id: :seance_public, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :ageMin %>
    <%= form.number_field :ageMin, id: :seance_ageMin, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :ageMax %>
    <%= form.number_field :ageMax, id: :seance_ageMax, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :niveau %>
    <%= form.text_field :niveau, id: :seance_niveau, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :sexe %>
    <%= form.number_field :sexe, id: :seance_sexe, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :periode %>
    <%= form.text_field :periode, id: :seance_periode, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :jour %>
    <%= form.text_field :jour, id: :seance_jour, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :heureDebut %>
    <%= form.time_select :heureDebut, id: :seance_heureDebut, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :heureFin %>
    <%= form.time_select :heureFin, id: :seance_heureFin, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :dateDebut %>
    <%= form.date_select :dateDebut, id: :seance_dateDebut, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :dateFin %>
    <%= form.date_select :dateFin, id: :seance_dateFin, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :tarif %>
    <%= form.text_field :tarif, id: :seance_tarif, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :Place %>
    <%= form.select :place_id, Place.all.collect { |pl| [ pl.name, pl.id ] }, include_blank: false, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :Activite %>
    <%= form.select :activite_id, Activite.all.collect { |a| [ a.nom, a.id ] }, include_blank: false, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :Structure %>
    <%= form.select :structure_id, Structure.all.collect { |s| [ s.name, s.id ] }, include_blank: false, class:"form-control" %>
  </div>

  <div class="btn btn-primary">
    <%= form.submit %>
  </div>
<% end %>

app/views/seances/edit.html.erb
<h1>Editing Seance</h1>

<%= render 'form', seance: @seance %>

<%= link_to 'Show', @seance,class:"badge badge-primary" %> |
<%= link_to 'Back', seances_path,class:"badge badge-primary" %>

app/views/seances/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Seances</h1>

<table class="table" style="font-size:11px;">
  <thead class="thead-dark">
    <tr>
      <th>Public</th>
      <th>Agemin</th>
      <th>Agemax</th>
      <th>Niveau</th>
      <th>Sexe</th>
      <th>Periode</th>
      <th>Jour</th>
      <th>Heuredebut</th>
      <th>Heurefin</th>
      <th>Datedebut</th>
      <th>Datefin</th>
      <th>Tarif</th>
      <th>Place</th>
      <th>Activité</th>
      <th>Structure</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @seances.each do |seance| %>
      <tr>
        <td><%= seance.public %></td>
        <td><%= seance.ageMin %></td>
        <td><%= seance.ageMax %></td>
        <td><%= seance.niveau %></td>
        <td><%= seance.sexe %></td>
        <td><%= seance.periode %></td>
        <td><%= seance.jour %></td>
        <td><%= seance.heureDebut %></td>
        <td><%= seance.heureFin %></td>
        <td><%= seance.dateDebut %></td>
        <td><%= seance.dateFin %></td>
        <td><%= seance.tarif %></td>
        <td><%= seance.place.name %></td>
        <td><%= seance.activite.nom%></td>
        <td><%= seance.structure.name %></td>
        <td><%= link_to 'Show', seance, class:"badge badge-primary" %></td>
        <td><%= link_to 'Edit', edit_seance_path(seance), class:"badge badge-primary" %></td>
        <td><%= link_to 'Destroy', seance, method: :delete, data: { confirm: 'Are you sure?' }, class:"badge badge-primary" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Seance', new_seance_path, class:"badge badge-primary" %>

app/views/seances/new.html.erb
<h1>New Seance</h1>

<%= render 'form', seance: @seance %>

<%= link_to 'Back', seances_path, class:"badge badge-primary" %>

app/views/seances/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Public:</strong>
  <%= @seance.public %>
</p>

<p>
  <strong>Agemin:</strong>
  <%= @seance.ageMin %>
</p>

<p>
  <strong>Agemax:</strong>
  <%= @seance.ageMax %>
</p>

<p>
  <strong>Niveau:</strong>
  <%= @seance.niveau %>
</p>

<p>
  <strong>Sexe:</strong>
  <%= @seance.sexe %>
</p>

<p>
  <strong>Periode:</strong>
  <%= @seance.periode %>
</p>

<p>
  <strong>Jour:</strong>
  <%= @seance.jour %>
</p>

<p>
  <strong>Heuredebut:</strong>
  <%= @seance.heureDebut %>
</p>

<p>
  <strong>Heurefin:</strong>
  <%= @seance.heureFin %>
</p>

<p>
  <strong>Datedebut:</strong>
  <%= @seance.dateDebut %>
</p>

<p>
  <strong>Datefin:</strong>
  <%= @seance.dateFin %>
</p>

<p>
  <strong>Tarif:</strong>
  <%= @seance.tarif %>
</p>

<p>
  <strong>place:</strong>
  <%= @seance.place.name %>
</p>

<p>
  <strong>Activité:</strong>
  <%= @seance.activite.nom %>
</p>

<p>
  <strong>Structure:</strong>
  <%= @seance.structure.name %>
</p>

<%= link_to 'Edit', edit_seance_path(@seance), class:"badge badge-primary" %> |
<%= link_to 'Back', seances_path, class:"badge badge-primary" %>