config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :seances
  resources :activites
  resources :directions
  resources :structures
  resources :posts
  resources :places

  root 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/activite.rb
class Activite < ApplicationRecord
end

app/controllers/activites_controller.rb
class ActivitesController < ApplicationController
  before_action :set_activite, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /activites
  # GET /activites.json
  def index
    @activites = Activite.all
  end

  # GET /activites/1
  # GET /activites/1.json
  def show
  end

  # GET /activites/new
  def new
    @activite = Activite.new
  end

  # GET /activites/1/edit
  def edit
  end

  # POST /activites
  # POST /activites.json
  def create
    @activite = Activite.new(activite_params)

    respond_to do |format|
      if @activite.save
        format.html { redirect_to @activite, notice: 'Activite was successfully created.' }
        format.json { render :show, status: :created, location: @activite }
      else
        format.html { render :new }
        format.json { render json: @activite.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /activites/1
  # PATCH/PUT /activites/1.json
  def update
    respond_to do |format|
      if @activite.update(activite_params)
        format.html { redirect_to @activite, notice: 'Activite was successfully updated.' }
        format.json { render :show, status: :ok, location: @activite }
      else
        format.html { render :edit }
        format.json { render json: @activite.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activites/1
  # DELETE /activites/1.json
  def destroy
    @activite.destroy
    respond_to do |format|
      format.html { redirect_to activites_url, notice: 'Activite was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_activite
      @activite = Activite.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def activite_params
      params.require(:activite).permit(:nom)
    end
end

app/helpers/activites_helper.rb
module ActivitesHelper
end

app/views/activites/_form.html.erb
<%= form_with(model: activite, local: true) do |form| %>
  <% if activite.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(activite.errors.count, "error") %> prohibited this activite from being saved:</h2>

      <ul>
      <% activite.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :nom %>
    <%= form.text_field :nom, id: :activite_nom, class:"form-control" %>
  </div>

  <div class="btn btn-primary">
    <%= form.submit %>
  </div>
<% end %>

app/views/activites/edit.html.erb
<h1>Editing Activite</h1>

<%= render 'form', activite: @activite %>

<%= link_to 'Show', @activite, class:"badge badge-primary" %> |
<%= link_to 'Back', activites_path, class:"badge badge-primary" %>

app/views/activites/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Activites</h1>

<table class="table">
  <thead class="thead-dark">
    <tr>
      <th>Nom</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @activites.each do |activite| %>
      <tr>
        <td><%= activite.nom %></td>
        <td><%= link_to 'Show', activite, class:"badge badge-primary" %></td>
        <td><%= link_to 'Edit', edit_activite_path(activite), class:"badge badge-primary" %></td>
        <td><%= link_to 'Destroy', activite, method: :delete, data: { confirm: 'Are you sure?' }, class:"badge badge-primary" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Activite', new_activite_path, class:"badge badge-primary" %>

app/views/activites/new.html.erb
<h1>New Activite</h1>

<%= render 'form', activite: @activite %>

<%= link_to 'Back', activites_path, class:"badge badge-primary" %>

app/views/activites/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nom:</strong>
  <%= @activite.nom %>
</p>

<%= link_to 'Edit', edit_activite_path(@activite), class:"badge badge-primary" %> |
<%= link_to 'Back', activites_path, class:"badge badge-primary" %>