config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :seances
  resources :activites
  resources :directions
  resources :structures
  resources :posts
  resources :places

  root 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @titre %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap-theme.css">

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <header>
        <h1>Base de connaissances Chatbot</h1>

        <nav>
          <p class="navbar-text pull-right">
              <% if user_signed_in? %>
                Bienvenue <strong><%= current_user.email %></strong>.
                <%= link_to 'Modifier profil', edit_user_registration_path, :class => 'navbar-link' %> |
                <%= link_to "Déconnection", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
              <% else %>
                <%= link_to "Inscription", new_user_registration_path, :class => 'navbar-link'  %> |
                <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
              <% end %>
          </p>
          <ul class="nav nav-pills nav-fil">
            <li><%= link_to "Home", root_path, class:"nav-link"%></li>
            <li><%= link_to "Structure", structures_path, class:"nav-link" %></li>
            <li><%= link_to "Direction", directions_path, class:"nav-link" %></li>
            <li><%= link_to "Place", places_path, class:"nav-link" %></li>
            <li><%= link_to "Activite", activites_path, class:"nav-link" %></li>
            <li><%= link_to "Seances", seances_path, class:"nav-link" %></li>
          </ul>
        </nav>
      </header>
      <section>
        <%= yield %>
      </section>
    </div>
  </body>
</html>